# Generated by Django 4.2.7 on 2025-10-18 15:26

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('image', '图片'), ('video', '视频'), ('pdf', 'PDF'), ('document', '文档'), ('spreadsheet', '表格')], default='image', max_length=20, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.document_upload_path, verbose_name='文件'),
        ),
    ]
