# Generated by Django 4.2.7 on 2025-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_remarks_document_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='allowed_file_types',
            field=models.JSONField(blank=True, default=list, help_text='允许的文件类型列表，如 ["image", "video", "pdf"]，空列表表示允许所有类型', verbose_name='允许的文件类型'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='max_file_count',
            field=models.IntegerField(default=0, help_text='每个资料类型最多允许上传的文件数，0 表示不限制', verbose_name='最大文件数'),
        ),
    ]
