# Generated by Django 4.2.7 on 2025-10-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('status', models.CharField(choices=[('pending', '资料收集中'), ('complete', '资料已齐全'), ('reviewing', '审核中'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
