# Generated by Django 4.2.7 on 2025-10-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='字段名称')),
                ('field_type', models.CharField(choices=[('text', '文本'), ('number', '数字'), ('date', '日期'), ('select', '下拉菜单'), ('textarea', '多行文本'), ('email', '邮箱'), ('phone', '手机号'), ('url', '网址')], default='text', max_length=20, verbose_name='字段类型')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True, verbose_name='占位符')),
                ('help_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='帮助文本')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值')),
                ('options', models.JSONField(blank=True, default=list, help_text='下拉菜单的选项，格式: ["选项1", "选项2", "选项3"]', verbose_name='选项列表')),
                ('min_length', models.IntegerField(blank=True, null=True, verbose_name='最小长度')),
                ('max_length', models.IntegerField(blank=True, null=True, verbose_name='最大长度')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='最小值')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='最大值')),
                ('regex_pattern', models.CharField(blank=True, max_length=255, null=True, verbose_name='正则表达式')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '自定义字段',
                'verbose_name_plural': '自定义字段',
                'db_table': 'custom_fields',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True, verbose_name='字段值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='customers.customfield', verbose_name='自定义字段')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '自定义字段值',
                'verbose_name_plural': '自定义字段值',
                'db_table': 'custom_field_values',
                'ordering': ['custom_field__sort_order', 'id'],
                'unique_together': {('customer', 'custom_field')},
            },
        ),
    ]
